micronaut:
  application:
    name: dev.amatos.restcountries
  router.static-resources.default:
    enabled: true
    paths: classpath:static
    mapping: "/**"
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /openapi/**
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedMethods:
          - GET
  caches:
    rate-limiter:
      expire-after-access: 10m
rate-limiter:
  timeout-duration: 100ms
  limit-refresh-period: 5s
  limit-for-period: 5