micronaut:
  application:
    name: dev.amatos.restcountries
  router.static-resources.default:
    enabled: true
    paths: classpath:static
    mapping: "/**"
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedMethods:
          - GET